export const LOGIN_POST_REQUEST = "LOGIN_POST_REQUEST"
export const LOGIN_POST_SUCCESS = "LOGIN_POST_SUCCESS"
export const LOGIN_POST_FAILURE = "LOGIN_POST_FAILURE"

export const REGISTER_POST_REQUEST = "REGISTER_POST_REQUEST"
export const REGISTER_POST_SUCCESS = "REGISTER_POST_SUCCESS"
export const REGISTER_POST_FAILURE = "REGISTER_POST_FAILURE"

export const POST_POST_REQUEST = "POST_POST_REQUEST"
export const POST_POST_SUCCESS = "POST_POST_SUCCESS"
export const POST_POST_FAILIUR = "POST_POST_FAILIUR"

export const POST_GET_REQUEST = "POST_GET_REQUEST"
export const POST_GET_SUCCESS = "POST_GET_SUCCESS"
export const POST_GET_FAILIUR = "POST_GET_FAILIUR"